config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Dashboard
  get "/dashboard" => "admins#index"
  get "profile/:username" => "admins#profile", as: :profile

  resources :posts, only: [:new, :create, :show]

  root to: "public#homepage"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  

  has_many :posts

  def full_name
    "#{first_name} #{last_name}" 
  end

  def total_followers
    0
  end
  def total_following
    0
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :admin
	before_create :set_active

	scope :active, -> {where active: true}

	def set_active
		self.active = true
	end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
	before_action :set_admin, only: [:profile]

	#Dashboard
	def index
		@posts = Post.active
	end

	def profile
		
	end
	def set_admin
		@admin = Admin.find_by_username(params[:username])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:admin_update, keys: [:username, :first_name, :last_name, :image, :image_cache])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :password])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  # def index
  #   @posts = Post.all
  # end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.admin_id = current_admin.id if admin_signed_in?

      if @post.save
        redirect_to dashboard_path, flash: { success: "Publicado com Sucesso"} 
      else
        redirect_to new_post_path, flash: { danger: "Ocorreu Erro ao Publicar!"} 
      end
    end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:image, :image_cache, :active)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
	def homepage
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admins/index.html.erb
<%#= @posts.inspect %>

<div class="container">
	<div class="row">
		<div class="col-8">
			<% @posts.each do |post| %>
			<div class="insta-post">
				<div class="post-meta">
					<%= post.admin.username %>
				</div>
				<%= image_tag post.image.url, class: "img img-fluid" %>
			</div>
			<% end -%>			
		</div>
		<div class="col-4">
			<div class="admin-summary">
				<p><strong><%= current_admin.username %></strong> <br />
				<%= current_admin.full_name %></p>
			</div>
			<div class="follower-suggestions">
				
			</div>
		</div>
	</div>
</div>

app/views/admins/profile.html.erb
<div class="container">
	<div class="row">
		<div class="col-4">
			<%#= image_tag @admin.image.url, width: "200px", class: "img-rounded" %>
		</div>
		<div class="col-8 text-left">
			<h1><%= @admin.full_name %></h1>
			<%= link_to "Editar Perfil",edit_admin_registration_path, class: "btn btn-secondary" %>
			<div class="profile-stats"><%= @admin.posts.count %> publicações</div>
			<div class="profile-stats"><%= @admin.total_followers%> seguidores</div>
			<div class="profile-stats"><%= @admin.total_following %> seguindo</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Instagram Clone</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Instagram Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <% if admin_signed_in? %>
                        <%= render "layouts/nav/admin_nav" %>
                    <% else %>
                        <%= render "layouts/nav/public_nav" %>
                    <% end -%>

                </ul>
            </div>
        </div>
    </nav>
    <!-- Page content-->
    <div class="container">
        <div class="col-lg-12">
            <%= yield %>
        </div>
    </div>
</body>
</html>

app/views/layouts/nav/_admin_nav.html.erb
<li class="nav-item">
	<%= link_to "Home", dashboard_path, class: "nav-link" %>
</li>
<li class="nav-item">
	<%= link_to "New Post", new_post_path, class: "nav-link" %>
</li>
<li class="nav-item">
	<%= link_to "My Profile", profile_path(current_admin.username), class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: "nav-link"%>
</li>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <div class="">
    <%= f.file_field :image, class: "form-control"%>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="">
    <%= f.submit "Compartilhar", class: "btn btn-primary", data: { disable_with: "Compartilhando..."}%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.image %></td>
        <td><%= post.active %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

<%= link_to 'Back' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>Active:</strong>
  <%= @post.active %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>